import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";

import FooterComponent from "./common/Footer";
import NewsLetter from "./common/NewsLetter";
import FootBox from "./common/FootBox";
import Wrapper from "./common/Wrapper";
import HeadComponent from "./common/HeadComponent";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// or Dynamic metadata
export async function generateMetadata({ params }) {
  return {
    title: "Explore Dehradun",
    description: "Generated by create next app",
  };
}
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Product",
  // name: product.name,
  // image: product.image,
  // description: product.description,
  // sku: product.sku,
  // mpn: product.mpn,
  // brand: {
  //   '@type': 'Brand',
  //   name: product.brand,
  // },
  offers: {
    "@type": "Offer",
    // url: product.url,
    priceCurrency: "USD",
    // price: product.price,
    priceValidUntil: "2023-11-20",
    itemCondition: "https://schema.org/NewCondition",
    availability: "https://schema.org/InStock",
  },
};
// <!-- Google tag (gtag.js) -->
const scriptContent = `
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());
    gtag("config", "G-PVSSTTYLD0");
    `;
// <!-- Google tag (gtag.js) -->
const script2Content = `
     window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "AW-871785025");`;
// Conversion tracking script
const conversionScript = `
  gtag('event', 'conversion', { 'send_to': 'AW-871785025/HJXNCJav-NUBEMHE2Z8D' });
`;
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Google Tag Manager Script */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-PVSSTTYLD0"
        ></script>
        <script dangerouslySetInnerHTML={{ __html: scriptContent }} />
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-871785025"
        ></script>
        <script dangerouslySetInnerHTML={{ __html: script2Content }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* Conversion Tracking Script */}
      <script
        dangerouslySetInnerHTML={{
          __html: conversionScript,
        }}
      ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <!-- Google Tag Manager (noscript) --> */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KPZZTNKL"
            height="0"
            width="0"
            class="d-none visibility-hidden"
          ></iframe>
        </noscript>
        {/* <!-- End Google Tag Manager (noscript) --> */}
        <HeadComponent />
        {children}
        <Wrapper colClassName="col4">
          <FooterComponent>
            <NewsLetter></NewsLetter>
            <FootBox>
              <h2>Explore Dehradun with Us</h2>
              <ul>
                <li>
                  <a href="#">Explore Dehradun's Attractions</a>
                </li>
                <li>
                  <a href="#">Discover Local Cuisine in Dehradun</a>
                </li>
                <li>
                  <a href="#">Plan Your Adventure in the Himalayas</a>
                </li>
                <li>
                  <a href="#">Experience Spiritual Retreats</a>
                </li>
                <li className="last">
                  <a href="#">Learn About Dehradun's History</a>
                </li>
              </ul>
            </FootBox>
            <FootBox>
              <h2>Contact Us</h2>
              <ul>
                <li>
                  Email:{" "}
                  <a href="mailto:hivalikanthi@gmail.com">
                    hivalikanthi@gmail.com
                  </a>
                </li>
                <li>
                  Address: Village Patal, Pauri Garhwal, Uttarakhand, India
                </li>
                {/* <!-- <li>Phone: <a href="tel:+911234567890">+91 123 456 7890</a></li> --> */}
                <li className="last">
                  <a href="https://exploredehradun.in/privacy-policy/">
                    Privacy Policy
                  </a>
                </li>
              </ul>
            </FootBox>
            <br className="clear" />
          </FooterComponent>
        </Wrapper>
      </body>
    </html>
  );
}
